version: '3.8'
services:

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      BOOTSTRAP_SERVERS: broker:9092


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"

