version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 run:app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb

volumes:
  postgres_data:
